const aerobic = [
  {
    outOfStock: true,
    id: "speedRope",
    name: "Speed Rope",
    price: "16.99",
    weight: "100",
    url: "http://villainusa.com/products",
    categories: "aerobic",
    width: "6",
    length: "15",
    height: "6",
    quantity: "1",
    custom2Name: "Color",
    custom2Options: "Black|Red|Blue|Pink",
    custom2Value: "Black",
    img: "speedRope1",
    specs: {
      Material: "Steel cord, nylon coating",
      Length: "3m (variable)",
      "Grip Length": "12cm",
      Diameter: "2.8mm",
    },
  },

  {
    outOfStock: true,
    id: "agilityLadder",
    name: "Agility Ladder",
    price: "68.99",
    weight: "2500",
    url: "http://villainusa.com/products",
    categories: "aerobic",
    width: "25",
    length: "40",
    height: "5",
    quantity: "1",
    img: "agilityLadder1",
    specs: {
      Length: "9m",
      Width: "40cm",
      Sections: "4 (total length: 36m)",
      Connection: "Snap",
    },
  },

  {
    outOfStock: true,
    id: "agilityHurdles",
    name: "Agility Hurdle Set",
    price: "51.99",
    weight: "2500",
    url: "http://villainusa.com/products",
    categories: "aerobic",
    width: "46",
    length: "30",
    height: "30",
    quantity: "1",
    img: "agilityHurdles1",
    specs: {
      Material: "PVC",
      Lengths: "6in, 9in, 12in",
      Width: "18in",
      Includes: "3 hurdles (one of each height)",
    },
  },

  {
    outOfStock: true,
    id: "balanceBall",
    name: "Balance Ball",
    price: "114.99",
    weight: "5000",
    url: "http://villainusa.com/products",
    categories: "aerobic",
    width: "65",
    length: "65",
    height: "30",
    quantity: "1",
    img: "balanceBall1",
    specs: {
      Material: "ABS rubber, PVC plastic",
      Diameter: "65cm",
      "Ball Height": "22mm",
      Includes: "Anchored resistance band handles",
    },
  },
  {
    outOfStock: true,
    id: "aerobicStepper",
    name: "Aerobic Stepper",
    price: "79.99",
    weight: "4000",
    url: "http://villainusa.com/products",
    categories: "aerobic",
    width: "41",
    length: "109",
    height: "40",
    quantity: "1",
    img: "aerobicStepper1",
    specs: {
      Length: "109cm",
      Width: "41cm",
      Height: "20cm (top step), 10cm (bottom spacers)",
      Includes: "1 top step, 4 bottom spacers (two pairs)",
    },
  },
];

export default aerobic;
