const barbells = [
  {
    id: "15kgCompBar",
    name: "Women's 15kg Competition Bar",
    price: "327.75",
    weight: "15000",
    url: "",
    categories: "barbells",
    width: "10",
    length: "200",
    height: "10",
    quantity: "1",
    img: "15kgCompBar1",
    specs: {
      Weight: "15kg",
      Length: "2 Meters",
      "Tensile Strength": "200,000lbs",
      Bearing: "8pc Needle Bearing",
      "Center Knurling": "No",
      "Knurling Marks": "Single",
      "Knurling Depth": "1.2mm",
      Coating: "Chrome Shaft & Sleeve",
      "Shaft Diameter": "25mm",
    },
  },

  {
    id: "15kgTrainingBar",
    name: "Women's 15kg Training Bar",
    price: "199.99",
    weight: "15000",
    url: "",
    categories: "barbells",
    width: "10",
    length: "200",
    height: "10",
    quantity: "1",
    img: "15kgTrainingBar1",
    specs: {
      Weight: "15kg",
      Length: "2 Meters",
      "Tensile Strength": "200,000lbs",
      Bearing: "8pc Needle Bearing",
      "Center Knurling": "No",
      "Knurling Marks": "Double",
      "Knurling Depth": "1.2mm",
      Coating: "Chrome Shaft & Sleeve",
      "Shaft Diameter": "25mm",
    },
  },

  {
    id: "20kgCompBar",
    name: "Men's 20kg Competition Bar",
    price: "344.99",
    weight: "20000",
    url: "",
    categories: "barbells",
    width: "10",
    length: "220",
    height: "10",
    quantity: "1",
    img: "20kgCompBar1",
    specs: {
      Weight: "20kg",
      Length: "2.2 Meters",
      "Tensile Strength": "200,000lbs",
      Bearing: "8pc Needle Bearing",
      "Center Knurling": "Yes",
      "Knurling Marks": "Single",
      "Knurling Depth": "1.2mm",
      Coating: "Chrome Shaft & Sleeve",
      "Shaft Diameter": "28mm",
    },
  },

  {
    id: "20kgTrainingBar",
    name: "Men's 20kg Training Bar",
    price: "219.99",
    weight: "20000",
    url: "",
    categories: "barbells",
    width: "10",
    length: "220",
    height: "10",
    quantity: "1",
    img: "20kgTrainingBar1",
    specs: {
      Weight: "20kg",
      Length: "2.2 Meters",
      "Tensile Strength": "200,000lbs",
      Bearing: "8pc Needle Bearing",
      "Center Knurling": "Yes",
      "Knurling Marks": "Double",
      "Knurling Depth": "1.2mm",
      Coating: "Chrome Shaft & Sleeve",
      "Shaft Diameter": "28mm",
    },
  },

  {
    id: "hexBar",
    name: "Hex Bar",
    price: "219.99",
    weight: "38000",
    url: "",
    categories: "barbells",
    width: "100",
    length: "140",
    height: "20",
    quantity: "1",
    img: "hexBar1",
    specs: {
      Weight: "38kg",
      Length: "1.4m",
      Coating: "Chrome Shaft & Sleeve",
    },
  },

  {
    id: "techniqueBar",
    name: "Technique Bar",
    price: "114.99",
    weight: "6804",
    url: "",
    categories: "barbells",
    width: "10",
    length: "183",
    height: "10",
    quantity: "1",
    img: "techniqueBar1",
    specs: {
      Weight: "15lbs",
      Length: "6ft",
      "Weight Capacity": "200lbs",
      "Knurling Marks": "Single",
      "Knurling Depth": "1.2mm",
    },
  },
];

export default barbells;
