const bodyweight = [
  {
    id: "suspensionTrainer",
    name: "Suspension Trainer",
    price: "119.99",
    weight: "500",
    url: "",
    categories: "bodyweight",
    width: "15",
    length: "15",
    height: "15",
    quantity: "1",
    img: "suspensionTrainer1",
    specs: {
      Material: "Nylon strap, alloy buckle",
      "Adjustable Range": "1.5 - 3.4 meters",
    },
  },

  {
    id: "abMat",
    name: "Ab Mat",
    price: "24.99",
    weight: "500",
    url: "",
    categories: "bodyweight",
    width: "30",
    length: "36",
    height: "6",
    quantity: "1",
    img: "abMat1",
    specs: {
      Material: "High quality PU leather",
      Length: "36cm",
      Width: "30cm",
      Height: "6.2cm",
    },
  },

  {
    id: "climbingRope",
    name: "Climbing Rope",
    categories: "bodyweight",
    price: " (Select Length To See Price)",
    img: "climbingRope1",
    specs: {
      Material: "Hemp rope, alloy eyelet",
      "Rope Diameter": "38mm",
      "Eyelet Diameter": "50mm",
    },
    data: [
      {
        id: "climbingRope3m",
        name: "3m Climbing Rope",
        price: "54.99",
        weight: "6000",
        url: "",
        categories: "bodyweight",
        width: "35",
        length: "35",
        height: "35",
        quantity: "1",
        img: "climbingRope1",
      },
      {
        id: "climbingRope4m",
        name: "4m Climbing Rope",
        price: "59.99",
        weight: "7500",
        url: "",
        categories: "bodyweight",
        width: "35",
        length: "35",
        height: "35",
        quantity: "1",
        img: "climbingRope1",
      },
      {
        id: "climbingRope5m",
        name: "5m Climbing Rope",
        price: "67.99",
        weight: "9000",
        url: "",
        categories: "bodyweight",
        width: "35",
        length: "35",
        height: "35",
        quantity: "1",
        img: "climbingRope1",
      },
    ],
  },

  {
    id: "gymnasticRings",
    name: "Wooden Gymnastic Rings",
    price: "64.99",
    weight: "1000",
    url: "",
    categories: "bodyweight",
    width: "20",
    length: "20",
    height: "8",
    quantity: "1",
    img: "gymnasticRings1",
    specs: {
      Material: "Birch wood rings, nylon strap, alloy buckle",
      "Inner Diameter": "18cm",
      "Ring Thickness": "28mm",
      "Strap Length": "5.5m",
      "Max Load Capacity": "680kg",
    },
  },
];

export default bodyweight;
