const jumpBoxes = [
  {
    outOfStock: true,
    id: "woodenJumpBox",
    name: "3-in-1 Wooden Plyo Jump Box",
    price: "129.99",
    weight: "1500",
    url: "http://villainusa.com/products",
    categories: "boxes",
    width: "76",
    length: "61",
    height: "51",
    quantity: "1",
    img: "woodenJumpBox1",
    specs: {
      Dimensions: "20in x 24in x 30in",
      Material: "Wood Composite",
    },
  },

  {
    id: "foamJumpBox",
    name: "Foam Jump Boxes",
    categories: "boxes",
    img: "foamJumpBox1",
    price: " (Select Plate To See Price)",
    specs: {
      Length: "90cm",
      Width: "76cm",
      Height: "3, 6, 12, 18, and 24 inches",
    },
    data: [
      {
        outOfStock: true,
        id: "3inBox",
        name: "3in Foam Jump Box",
        price: "109.99",
        weight: "3500",
        url: "http://villainusa.com/products",
        categories: "boxes",
        width: "76",
        length: "90",
        height: "8",
        quantity: "1",
        img: "foamJumpBox1",
      },
      {
        outOfStock: true,
        id: "6inBox",
        name: "6in Foam Jump Box",
        price: "174.99",
        weight: "5500",
        url: "http://villainusa.com/products",
        categories: "boxes",
        width: "76",
        length: "90",
        height: "15",
        quantity: "1",
        img: "foamJumpBox1",
      },
      {
        outOfStock: true,
        id: "12inBox",
        name: "12in Foam Jump Box",
        price: "224.99",
        weight: "9500",
        url: "http://villainusa.com/products",
        categories: "boxes",
        width: "76",
        length: "90",
        height: "30",
        quantity: "1",
        img: "foamJumpBox1",
      },
      {
        outOfStock: true,
        id: "18inBox",
        name: "18in Foam Jump Box",
        price: "279.99",
        weight: "13500",
        url: "http://villainusa.com/products",
        categories: "boxes",
        width: "76",
        length: "90",
        height: "46",
        quantity: "1",
        img: "foamJumpBox1",
      },
      {
        outOfStock: true,
        id: "24inBox",
        name: "24in Foam Jump Box",
        price: "329.99",
        weight: "15500",
        url: "http://villainusa.com/products",
        categories: "boxes",
        width: "76",
        length: "90",
        height: "61",
        quantity: "1",
        img: "foamJumpBox1",
      },
    ],
  },
];

export default jumpBoxes;
