const kettlebells = [
  // --------------------
  // COMPETITION POWDERED
  // --------------------
  {
    id: "kbCompetitionPowdered",
    name: "Powder Coated Competition Kettlebells",
    categories: "kettlebells",
    img: "kbCompetitionPowdered1",
    price: " (Select Kettlebell To See Price)",
    specs: {
      Coating: "Powder coated",
      "Weight Tolerance": "+/- 1%",
      Customization: "Available",
    },
    data: [
      {
        outOfStock: true,
        id: "kbcompetitionpowdered4kg",
        name: "4kg Powder-Coated Competition Kettlebell",
        price: "35.99",
        weight: "4000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbCompetitionPowdered1",
      },
      {
        outOfStock: true,
        id: "kbcompetitionpowdered6kg",
        name: "6kg Powder-Coated Competition Kettlebell",
        price: "39.99",
        weight: "6000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbCompetitionPowdered1",
      },
      {
        outOfStock: true,
        id: "kbcompetitionpowdered8kg",
        name: "8kg Powder-Coated Competition Kettlebell",
        price: "49.99",
        weight: "8000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbCompetitionPowdered1",
      },
      {
        outOfStock: true,
        id: "kbcompetitionpowdered10kg",
        name: "10kg Powder-Coated Competition Kettlebell",
        price: "59.99",
        weight: "10000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbCompetitionPowdered1",
      },
      {
        outOfStock: true,
        id: "kbcompetitionpowdered12kg",
        name: "12kg Powder-Coated Competition Kettlebell",
        price: "69.99",
        weight: "12000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbCompetitionPowdered1",
      },
      {
        outOfStock: true,
        id: "kbcompetitionpowdered14kg",
        name: "14kg Powder-Coated Competition Kettlebell",
        price: "74.99",
        weight: "14000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbCompetitionPowdered1",
      },
      {
        outOfStock: true,
        id: "kbcompetitionpowdered16kg",
        name: "16kg Powder-Coated Competition Kettlebell",
        price: "79.99",
        weight: "16000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbCompetitionPowdered1",
      },
      {
        outOfStock: true,
        id: "kbcompetitionpowdered18kg",
        name: "18kg Powder-Coated Competition Kettlebell",
        price: "84.99",
        weight: "18000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbCompetitionPowdered1",
      },
      {
        outOfStock: true,
        id: "kbcompetitionpowdered20kg",
        name: "20kg Powder-Coated Competition Kettlebell",
        price: "89.99",
        weight: "20000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbCompetitionPowdered1",
      },
      {
        outOfStock: true,
        id: "kbcompetitionpowdered22kg",
        name: "22kg Powder-Coated Competition Kettlebell",
        price: "94.99",
        weight: "22000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbCompetitionPowdered1",
      },
      {
        outOfStock: true,
        id: "kbcompetitionpowdered24kg",
        name: "24kg Powder-Coated Competition Kettlebell",
        price: "99.99",
        weight: "24000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbCompetitionPowdered1",
      },
    ],
  },
  // -----------------
  // COMPETITION VINYL
  // -----------------
  {
    id: "kbCompetitionVinyl",
    name: "Vinyl Coated Competition Kettlebells",
    categories: "kettlebells",
    img: "kbCompetitionVinyl1",
    price: " (Select Kettlebell To See Price)",
    specs: {
      Coating: "Vinyl coated",
      "Weight Tolerance": "+/- 1%",
      Customization: "Available",
    },
    data: [
      {
        outOfStock: true,
        id: "kbcompetitionvinyl4kg",
        name: "4kg Vinyl-Coated Competition Kettlebell",
        price: "49.99",
        weight: "4000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbCompetitionVinyl1",
      },
      {
        outOfStock: true,
        id: "kbcompetitionvinyl6kg",
        name: "6kg Vinyl-Coated Competition Kettlebell",
        price: "54.99",
        weight: "6000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbCompetitionVinyl1",
      },
      {
        outOfStock: true,
        id: "kbcompetitionvinyl8kg",
        name: "8kg Vinyl-Coated Competition Kettlebell",
        price: "64.99",
        weight: "8000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbCompetitionVinyl1",
      },
      {
        outOfStock: true,
        id: "kbcompetitionvinyl10kg",
        name: "10kg Vinyl-Coated Competition Kettlebell",
        price: "69.99",
        weight: "10000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbCompetitionVinyl1",
      },
      {
        outOfStock: true,
        id: "kbcompetitionvinyl12kg",
        name: "12kg Vinyl-Coated Competition Kettlebell",
        price: "74.99",
        weight: "12000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbCompetitionVinyl1",
      },
      {
        outOfStock: true,
        id: "kbcompetitionvinyl16kg",
        name: "16kg Vinyl-Coated Competition Kettlebell",
        price: "79.99",
        weight: "16000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbCompetitionVinyl1",
      },
      {
        outOfStock: true,
        id: "kbcompetitionvinyl18kg",
        name: "18kg Vinyl-Coated Competition Kettlebell",
        price: "84.99",
        weight: "18000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbCompetitionVinyl1",
      },
      {
        outOfStock: true,
        id: "kbcompetitionvinyl20kg",
        name: "20kg Vinyl-Coated Competition Kettlebell",
        price: "89.99",
        weight: "20000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbCompetitionVinyl1",
      },
      {
        outOfStock: true,
        id: "kbcompetitionvinyl22kg",
        name: "22kg Vinyl-Coated Competition Kettlebell",
        price: "94.99",
        weight: "22000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbCompetitionVinyl1",
      },
      {
        outOfStock: true,
        id: "kbcompetitionvinyl24kg",
        name: "24kg Vinyl-Coated Competition Kettlebell",
        price: "99.99",
        weight: "24000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbCompetitionVinyl1",
      },
      {
        outOfStock: true,
        id: "kbcompetitionvinyl28kg",
        name: "28kg Vinyl-Coated Competition Kettlebell",
        price: "114.99",
        weight: "28000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbCompetitionVinyl1",
      },
      {
        outOfStock: true,
        id: "kbcompetitionvinyl32kg",
        name: "32kg Vinyl-Coated Competition Kettlebell",
        price: "129.99",
        weight: "32000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbCompetitionVinyl1",
      },
    ],
  },
  // -----------------
  // TRAINING POWDERED
  // -----------------
  {
    id: "kbTrainingPowdered",
    name: "Powder Coated Training Kettlebells",
    categories: "kettlebells",
    img: "kbTrainingPowdered1",
    price: " (Select Kettlebell To See Price)",
    specs: {
      Coating: "Powder coated",
      "Weight Tolerance": "+/- 1%",
      Customization: "Available",
    },
    data: [
      {
        outOfStock: true,
        id: "kbtrainingpowdered4kg",
        name: "4kg Powder-Coated Training Kettlebell",
        price: "19.99",
        weight: "4000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbTrainingPowdered1",
      },
      {
        outOfStock: true,
        id: "kbtrainingpowdered6kg",
        name: "6kg Powder-Coated Training Kettlebell",
        price: "24.99",
        weight: "6000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbTrainingPowdered1",
      },
      {
        outOfStock: true,
        id: "kbtrainingpowdered8kg",
        name: "8kg Powder-Coated Training Kettlebell",
        price: "29.99",
        weight: "8000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbTrainingPowdered1",
      },
      {
        outOfStock: true,
        id: "kbtrainingpowdered12kg",
        name: "12kg Powder-Coated Training Kettlebell",
        price: "34.99",
        weight: "12000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbTrainingPowdered1",
      },
      {
        outOfStock: true,
        id: "kbtrainingpowdered16kg",
        name: "16kg Powder-Coated Training Kettlebell",
        price: "44.99",
        weight: "16000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbTrainingPowdered1",
      },
      {
        outOfStock: true,
        id: "kbtrainingpowdered20kg",
        name: "20kg Powder-Coated Training Kettlebell",
        price: "59.99",
        weight: "20000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbTrainingPowdered1",
      },
      {
        outOfStock: true,
        id: "kbtrainingpowdered24kg",
        name: "24kg Powder-Coated Training Kettlebell",
        price: "69.99",
        weight: "24000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbTrainingPowdered1",
      },
      {
        outOfStock: true,
        id: "kbtrainingpowdered28kg",
        name: "28kg Powder-Coated Training Kettlebell",
        price: "84.99",
        weight: "28000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbTrainingPowdered1",
      },
      {
        outOfStock: true,
        id: "kbtrainingpowdered32kg",
        name: "32kg Powder-Coated Training Kettlebell",
        price: "99.99",
        weight: "32000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbTrainingPowdered1",
      },
    ],
  },
  // --------------------
  // TRAINING VINYL
  // --------------------
  {
    id: "kbTrainingVinyl",
    name: "Vinyl Coated Training Kettlebells",
    categories: "kettlebells",
    img: "kbTrainingVinyl1",
    price: " (Select Kettlebell To See Price)",
    specs: {
      Coating: "Vinyl coated",
      "Weight Tolerance": "+/- 1%",
      Customization: "Available",
    },
    data: [
      {
        outOfStock: true,
        id: "kbtrainingvinyl2kg",
        name: "2kg Vinyl-Coated Training Kettlebell",
        price: "9.99",
        weight: "2000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbTrainingVinyl1",
      },
      {
        outOfStock: true,
        id: "kbtrainingvinyl4kg",
        name: "4kg Vinyl-Coated Training Kettlebell",
        price: "14.99",
        weight: "4000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbTrainingVinyl1",
      },
      {
        outOfStock: true,
        id: "kbtrainingvinyl6kg",
        name: "6kg Vinyl-Coated Training Kettlebell",
        price: "24.99",
        weight: "6000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbTrainingVinyl1",
      },
      {
        outOfStock: true,
        id: "kbtrainingvinyl8kg",
        name: "8kg Vinyl-Coated Training Kettlebell",
        price: "34.99",
        weight: "8000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbTrainingVinyl1",
      },
      {
        outOfStock: true,
        id: "kbtrainingvinyl10kg",
        name: "10kg Vinyl-Coated Training Kettlebell",
        price: "39.99",
        weight: "10000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbTrainingVinyl1",
      },
      {
        outOfStock: true,
        id: "kbtrainingvinyl12kg",
        name: "12kg Vinyl-Coated Training Kettlebell",
        price: "49.99",
        weight: "12000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbTrainingVinyl1",
      },
      {
        outOfStock: true,
        id: "kbtrainingvinyl16kg",
        name: "16kg Vinyl-Coated Training Kettlebell",
        price: "62.99",
        weight: "16000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbTrainingVinyl1",
      },
      {
        outOfStock: true,
        id: "kbtrainingvinyl20kg",
        name: "20kg Vinyl-Coated Training Kettlebell",
        price: "74.99",
        weight: "20000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbTrainingVinyl1",
      },
      {
        outOfStock: true,
        id: "kbtrainingvinyl24kg",
        name: "24kg Vinyl-Coated Training Kettlebell",
        price: "89.99",
        weight: "24000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbTrainingVinyl1",
      },
      {
        outOfStock: true,
        id: "kbtrainingvinyl28kg",
        name: "28kg Vinyl-Coated Training Kettlebell",
        price: "99.99",
        weight: "28000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbTrainingVinyl1",
      },
      {
        outOfStock: true,
        id: "kbtrainingvinyl32kg",
        name: "32kg Vinyl-Coated Training Kettlebell",
        price: "119.99",
        weight: "32000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbTrainingVinyl1",
      },
    ],
  },
];

export default kettlebells;
