const kettlebells = [
  // --------------------
  // COMPETITION POWDERED
  // --------------------
  {
    id: "kbCompetitionPowdered",
    name: "Powder Coated Competition Kettlebells",
    categories: "kettlebells",
    img: "kbCompetitionPowdered1",
    price: " (Select Kettlebell To See Price)",
    specs: {
      Coating: "Powder coated",
      "Weight Tolerance": "+/- 1%",
      Customization: "Available",
    },
    data: [
      {
        id: "kbcompetitionpowdered4kg",
        name: "4kg Powder-Coated Competition Kettlebell",
        price: "35.99",
        weight: "4000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbCompetitionPowdered1",
      },
      {
        id: "kbcompetitionpowdered6kg",
        name: "6kg Powder-Coated Competition Kettlebell",
        price: "35.99",
        weight: "6000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbCompetitionPowdered1",
      },
      {
        id: "kbcompetitionpowdered8kg",
        name: "8kg Powder-Coated Competition Kettlebell",
        price: "35.99",
        weight: "8000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbCompetitionPowdered1",
      },
      {
        id: "kbcompetitionpowdered10kg",
        name: "10kg Powder-Coated Competition Kettlebell",
        price: "35.99",
        weight: "10000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbCompetitionPowdered1",
      },
      {
        id: "kbcompetitionpowdered12kg",
        name: "12kg Powder-Coated Competition Kettlebell",
        price: "35.99",
        weight: "12000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbCompetitionPowdered1",
      },
      {
        id: "kbcompetitionpowdered14kg",
        name: "14kg Powder-Coated Competition Kettlebell",
        price: "41.99",
        weight: "14000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbCompetitionPowdered1",
      },
      {
        id: "kbcompetitionpowdered16kg",
        name: "16kg Powder-Coated Competition Kettlebell",
        price: "47.99",
        weight: "16000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbCompetitionPowdered1",
      },
      {
        id: "kbcompetitionpowdered18kg",
        name: "18kg Powder-Coated Competition Kettlebell",
        price: "53.99",
        weight: "18000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbCompetitionPowdered1",
      },
      {
        id: "kbcompetitionpowdered20kg",
        name: "20kg Powder-Coated Competition Kettlebell",
        price: "59.99",
        weight: "20000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbCompetitionPowdered1",
      },
      {
        id: "kbcompetitionpowdered22kg",
        name: "22kg Powder-Coated Competition Kettlebell",
        price: "65.99",
        weight: "22000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbCompetitionPowdered1",
      },
      {
        id: "kbcompetitionpowdered24kg",
        name: "24kg Powder-Coated Competition Kettlebell",
        price: "71.99",
        weight: "24000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbCompetitionPowdered1",
      },
    ],
  },
  // -----------------
  // COMPETITION VINYL
  // -----------------
  {
    id: "kbCompetitionVinyl",
    name: "Vinyl Coated Competition Kettlebells",
    categories: "kettlebells",
    img: "kbCompetitionVinyl1",
    price: " (Select Kettlebell To See Price)",
    specs: {
      Coating: "Vinyl coated",
      "Weight Tolerance": "+/- 1%",
      Customization: "Available",
    },
    data: [
      {
        id: "kbcompetitionvinyl4kg",
        name: "4kg Vinyl-Coated Competition Kettlebell",
        price: "47.99",
        weight: "4000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbCompetitionVinyl1",
      },
      {
        id: "kbcompetitionvinyl6kg",
        name: "6kg Vinyl-Coated Competition Kettlebell",
        price: "47.99",
        weight: "6000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbCompetitionVinyl1",
      },
      {
        id: "kbcompetitionvinyl8kg",
        name: "8kg Vinyl-Coated Competition Kettlebell",
        price: "47.99",
        weight: "8000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbCompetitionVinyl1",
      },
      {
        id: "kbcompetitionvinyl10kg",
        name: "10kg Vinyl-Coated Competition Kettlebell",
        price: "47.99",
        weight: "10000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbCompetitionVinyl1",
      },
      {
        id: "kbcompetitionvinyl12kg",
        name: "12kg Vinyl-Coated Competition Kettlebell",
        price: "42.99",
        weight: "12000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbCompetitionVinyl1",
      },
      {
        id: "kbcompetitionvinyl16kg",
        name: "16kg Vinyl-Coated Competition Kettlebell",
        price: "57.99",
        weight: "16000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbCompetitionVinyl1",
      },
      {
        id: "kbcompetitionvinyl18kg",
        name: "18kg Vinyl-Coated Competition Kettlebell",
        price: "65.99",
        weight: "18000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbCompetitionVinyl1",
      },
      {
        id: "kbcompetitionvinyl20kg",
        name: "20kg Vinyl-Coated Competition Kettlebell",
        price: "71.99",
        weight: "20000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbCompetitionVinyl1",
      },
      {
        id: "kbcompetitionvinyl22kg",
        name: "22kg Vinyl-Coated Competition Kettlebell",
        price: "77.99",
        weight: "22000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbCompetitionVinyl1",
      },
      {
        id: "kbcompetitionvinyl24kg",
        name: "24kg Vinyl-Coated Competition Kettlebell",
        price: "83.99",
        weight: "24000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbCompetitionVinyl1",
      },
      {
        id: "kbcompetitionvinyl28kg",
        name: "28kg Vinyl-Coated Competition Kettlebell",
        price: "95.99",
        weight: "28000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbCompetitionVinyl1",
      },
      {
        id: "kbcompetitionvinyl32kg",
        name: "32kg Vinyl-Coated Competition Kettlebell",
        price: "111.99",
        weight: "32000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbCompetitionVinyl1",
      },
    ],
  },
  // -----------------
  // TRAINING POWDERED
  // -----------------
  {
    id: "kbTrainingPowdered",
    name: "Powder Coated Training Kettlebells",
    categories: "kettlebells",
    img: "kbTrainingPowdered1",
    price: " (Select Kettlebell To See Price)",
    specs: {
      Coating: "Powder coated",
      "Weight Tolerance": "+/- 1%",
      Customization: "Available",
    },
    data: [
      {
        id: "kbtrainingpowdered4kg",
        name: "4kg Powder-Coated Training Kettlebell",
        price: "11.99",
        weight: "4000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbTrainingPowdered1",
      },
      {
        id: "kbtrainingpowdered6kg",
        name: "6kg Powder-Coated Training Kettlebell",
        price: "17.99",
        weight: "6000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbTrainingPowdered1",
      },
      {
        id: "kbtrainingpowdered8kg",
        name: "8kg Powder-Coated Training Kettlebell",
        price: "21.99",
        weight: "8000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbTrainingPowdered1",
      },
      {
        id: "kbtrainingpowdered12kg",
        name: "12kg Powder-Coated Training Kettlebell",
        price: "31.99",
        weight: "12000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbTrainingPowdered1",
      },
      {
        id: "kbtrainingpowdered16kg",
        name: "16kg Powder-Coated Training Kettlebell",
        price: "41.99",
        weight: "16000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbTrainingPowdered1",
      },
      {
        id: "kbtrainingpowdered20kg",
        name: "20kg Powder-Coated Training Kettlebell",
        price: "53.99",
        weight: "20000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbTrainingPowdered1",
      },
      {
        id: "kbtrainingpowdered24kg",
        name: "24kg Powder-Coated Training Kettlebell",
        price: "63.99",
        weight: "24000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbTrainingPowdered1",
      },
      {
        id: "kbtrainingpowdered28kg",
        name: "28kg Powder-Coated Training Kettlebell",
        price: "71.99",
        weight: "28000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbTrainingPowdered1",
      },
      {
        id: "kbtrainingpowdered32kg",
        name: "32kg Powder-Coated Training Kettlebell",
        price: "83.99",
        weight: "32000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbTrainingPowdered1",
      },
    ],
  },
  // --------------------
  // COMPETITION POWDERED
  // --------------------
  {
    id: "kbTrainingVinyl",
    name: "Vinyl Coated Training Kettlebells",
    categories: "kettlebells",
    img: "kbTrainingVinyl1",
    price: " (Select Kettlebell To See Price)",
    specs: {
      Coating: "Vinyl coated",
      "Weight Tolerance": "+/- 1%",
      Customization: "Available",
    },
    data: [
      {
        id: "kbtrainingvinyl2kg",
        name: "2kg Vinyl-Coated Training Kettlebell",
        price: "8.99",
        weight: "2000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbTrainingVinyl1",
      },
      {
        id: "kbtrainingvinyl4kg",
        name: "4kg Vinyl-Coated Training Kettlebell",
        price: "12.99",
        weight: "4000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbTrainingVinyl1",
      },
      {
        id: "kbtrainingvinyl6kg",
        name: "6kg Vinyl-Coated Training Kettlebell",
        price: "19.99",
        weight: "6000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbTrainingVinyl1",
      },
      {
        id: "kbtrainingvinyl8kg",
        name: "8kg Vinyl-Coated Training Kettlebell",
        price: "27.99",
        weight: "8000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbTrainingVinyl1",
      },
      {
        id: "kbtrainingvinyl10kg",
        name: "10kg Vinyl-Coated Training Kettlebell",
        price: "33.99",
        weight: "10000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbTrainingVinyl1",
      },
      {
        id: "kbtrainingvinyl12kg",
        name: "12kg Vinyl-Coated Training Kettlebell",
        price: "39.99",
        weight: "12000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbTrainingVinyl1",
      },
      {
        id: "kbtrainingvinyl16kg",
        name: "16kg Vinyl-Coated Training Kettlebell",
        price: "53.99",
        weight: "16000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbTrainingVinyl1",
      },
      {
        id: "kbtrainingvinyl20kg",
        name: "20kg Vinyl-Coated Training Kettlebell",
        price: "65.99",
        weight: "20000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbTrainingVinyl1",
      },
      {
        id: "kbtrainingvinyl24kg",
        name: "24kg Vinyl-Coated Training Kettlebell",
        price: "77.99",
        weight: "24000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbTrainingVinyl1",
      },
      {
        id: "kbtrainingvinyl28kg",
        name: "28kg Vinyl-Coated Training Kettlebell",
        price: "91.99",
        weight: "28000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbTrainingVinyl1",
      },
      {
        id: "kbtrainingvinyl32kg",
        name: "32kg Vinyl-Coated Training Kettlebell",
        price: "105.99",
        weight: "32000",
        url: "http://villainusa.com/products",
        categories: "kettlebells",
        width: "15",
        length: "15",
        height: "30",
        quantity: "1",
        img: "kbTrainingVinyl1",
      },
    ],
  },
];

export default kettlebells;
