const mobility = [
  {
    id: "massageBall",
    name: "Massage Ball",
    price: "5.99",
    weight: "400",
    url: "",
    categories: "mobility",
    width: "7",
    length: "7",
    height: "7",
    custom2Name: "Color",
    custom2Options: "Black|Red|Blue|Pink",
    custom2Value: "Black",
    quantity: "1",
    img: "massageBall1",
    specs: {
      Material: "Rubber",
      Diameter: "7cm",
      Color: "Choose within shopping cart",
    },
  },
  {
    id: "doubleMassageBall",
    name: "Double Massage Ball",
    price: "14.99",
    weight: "800",
    url: "",
    categories: "mobility",
    width: "7",
    length: "14",
    height: "7",
    quantity: "1",
    custom2Name: "Color",
    custom2Options:
      "Black|Gray|Orange|Red|Yellow|Lime Green|Yellow Orange|Blue|Pear Green",
    custom2Value: "Black",
    img: "doubleMassageBall1",
    specs: {
      Material: "Rubber",
      Diameter: "7cm",
      Color: "Choose within shopping cart",
    },
  },
  {
    id: "foamRoller",
    name: "Foam Roller",
    price: "24.99",
    weight: "500",
    url: "",
    categories: "mobility",
    width: "14",
    length: "33",
    height: "14",
    custom2Name: "Color",
    custom2Options: "Black|Blue|Purple|Pink|Green",
    custom2Value: "Black",
    quantity: "1",
    img: "foamRoller1",
    specs: {
      Material: "EVA foam and PVC plastic",
      Length: "33cm",
      Diameter: "14cm",
      Color: "Choose within shopping cart",
    },
  },
  {
    id: "yogaMat",
    name: "Yoga Mat",
    price: "14.99",
    weight: "1000",
    url: "",
    categories: "mobility",
    width: "61",
    length: "10",
    height: "10",
    custom2Name: "Thickness",
    custom2Options: "5mm|6mm|7mm",
    custom2Value: "5mm",
    quantity: "1",
    img: "yogaMat1",
    specs: {
      Material: "TPE (Thermoplastic Elastomers)",
      Features: "Anti-microbial, non-toxic, non-irritating",
      Length: "175cm",
      Width: "61cm",
      Thickness: "5, 6, or 7mm (choose thickness within shopping cart)",
    },
  },
  {
    id: "yogaBall",
    name: "Yoga Ball",
    price: "19.99",
    weight: "500",
    url: "",
    categories: "mobility",
    width: "10",
    length: "10",
    height: "10",
    quantity: "1",
    img: "yogaBall1",
    specs: {
      Material: "PVC",
      Diameter: "65cm",
    },
  },
  {
    id: "61cmBands",
    name: "61cm Resistance Bands",
    categories: "mobility",
    img: "61cmBands1",
    price: " (Select Band To See Price)",
    specs: {
      Length: "61cm total (30.5cm effective length)",
      Thickness: "4.5mm",
      "Weight Tolerance": "+/- 10g",
      "Red Band": "20lb resistance, 1.3cm width",
      "Purple Band": "40lb resistance, 1.9cm width",
      "Green Band": "60lb resistance, 2.9cm width",
    },
    data: [
      {
        id: "61cmBandsRed",
        name: "Red 61cm Resistance Band",
        price: "5.99",
        weight: "100",
        url: "",
        categories: "mobility",
        width: "10",
        length: "6",
        height: "4",
        quantity: "1",
        img: "61cmBands1",
      },
      {
        id: "61cmBandsPurple",
        name: "Purple 61cm Resistance Band",
        price: "7.99",
        weight: "200",
        url: "",
        categories: "mobility",
        width: "10",
        length: "6",
        height: "5",
        quantity: "1",
        img: "61cmBands1",
      },
      {
        id: "61cmBandsGreen",
        name: "Green 61cm Resistance Band",
        price: "9.99",
        weight: "300",
        url: "",
        categories: "mobility",
        width: "10",
        length: "6",
        height: "6",
        quantity: "1",
        img: "61cmBands1",
      },
    ],
  },
  {
    id: "208cmBands",
    name: "208cm Resistance Bands",
    categories: "mobility",
    img: "208cmBands1",
    price: " (Select Band To See Price)",
    specs: {
      Length: "208cm total (104cm effective length)",
      Thickness: "4.5mm",
      Material: "Latex",
      "Red Band": "25lb resistance, 1.3cm width",
      "Black Band": "50lb resistance, 2.2cm width",
      "Purple Band": "75lb resistance, 3.2cm width",
      "Green Band": "100lb resistance, 4.4cm width",
      "Blue Band": "140lb resistance, 6.4cm width",
      "Orange Band": "175lb resistance, 8.3cm width",
    },
    data: [
      {
        id: "208cmBandsRed",
        name: "Red 208cm Resistance Band",
        price: "12.99",
        weight: "100",
        url: "",
        categories: "mobility",
        width: "20",
        length: "6",
        height: "6",
        quantity: "1",
        img: "208cmBands1",
      },
      {
        id: "208cmBandsBlack",
        name: "Black 208cm Resistance Band",
        price: "13.99",
        weight: "200",
        url: "",
        categories: "mobility",
        width: "20",
        length: "6",
        height: "6",
        quantity: "1",
        img: "208cmBands1",
      },
      {
        id: "208cmBandsPurple",
        name: "Purple 208cm Resistance Band",
        price: "17.99",
        weight: "300",
        url: "",
        categories: "mobility",
        width: "20",
        length: "6",
        height: "6",
        quantity: "1",
        img: "208cmBands1",
      },
      {
        id: "208cmBandsGreen",
        name: "Green 208cm Resistance Band",
        price: "23.99",
        weight: "400",
        url: "",
        categories: "mobility",
        width: "20",
        length: "6",
        height: "6",
        quantity: "1",
        img: "208cmBands1",
      },
      {
        id: "208cmBandsBlue",
        name: "Blue 208cm Resistance Band",
        price: "29.99",
        weight: "500",
        url: "",
        categories: "mobility",
        width: "20",
        length: "6",
        height: "6",
        quantity: "1",
        img: "208cmBands1",
      },
      {
        id: "208cmBandsOrange",
        name: "Orange 208cm Resistance Band",
        price: "39.99",
        weight: "600",
        url: "",
        categories: "mobility",
        width: "20",
        length: "6",
        height: "6",
        quantity: "1",
        img: "208cmBands1",
      },
    ],
  },
];

export default mobility;
