const outfitting = [
  {
    id: "barbellFloorRack",
    name: "Barbell Floor Rack",
    price: "124.99",
    weight: "25000",
    url: "",
    categories: "outfitting",
    width: "45",
    length: "45",
    height: "25",
    quantity: "1",
    img: "barbellFloorRack1",
    specs: {
      Weight: "25kg",
      Length: "45cm",
      Width: "45cm",
      Height: "25cm",
    },
  },

  {
    id: "chalkBucket",
    name: "Chalk Bucket",
    price: "109.99",
    weight: "3000",
    url: "",
    categories: "outfitting",
    width: "45",
    length: "45",
    height: "800",
    quantity: "1",
    img: "chalkBucket1",
    specs: {
      Features: "Holds chalk!",
    },
  },

  {
    id: "beltHanger",
    name: "Belt & Band Hanger",
    price: "29.99",
    weight: "3000",
    url: "",
    categories: "outfitting",
    width: "14",
    length: "60",
    height: "13",
    quantity: "1",
    img: "beltHanger1",
    specs: {
      Hangers: "10",
      Length: "60cm",
      Width: "13.5cm",
      Height: "12.5cm",
    },
  },

  {
    id: "plateRack",
    name: "Bumper Plate Rack",
    price: "149.99",
    weight: "17500",
    url: "",
    categories: "outfitting",
    width: "34",
    length: "165",
    height: "30",
    quantity: "1",
    img: "plateRack1",
    specs: {
      Weight: "17.5kg",
      Length: "165cm",
      Width: "34cm",
      Height: "30cm",
    },
  },

  {
    id: "squatRack",
    name: "Squat Rack",
    price: "269.99",
    weight: "37500",
    url: "",
    categories: "outfitting",
    width: "71",
    length: "85",
    height: "60",
    quantity: "1",
    img: "squatRack1",
    specs: {
      Length: "85cm",
      Width: "71-120cm",
      Height: "86-167cm",
    },
  },

  {
    id: "jerkBlocks",
    name: "Jerk Blocks",
    price: "899.99",
    weight: "80000",
    url: "",
    categories: "outfitting",
    width: "102",
    length: "91",
    height: "90",
    quantity: "1",
    img: "jerkBlocks1",
    specs: {
      "Sold As A Pair": '"Quantity: 1" = 2 jerk block sets',
      Length: "36in",
      Width: "20in",
      Height: "15in, 12in, 6in, 2.25in (35.15in total height)",
    },
  },

  {
    id: "platform",
    name: "Weightlifting Platform",
    price: "949.99",
    weight: "126000",
    url: "",
    categories: "outfitting",
    width: "196",
    length: "244",
    height: "3",
    quantity: "1",
    img: "platform1",
    specs: {
      Weight: "126kg",
      Length: "196cm",
      Width: "244cm",
      Height: "3cm",
    },
  },
];

export default outfitting;
