import hardnessModal from "./../components/hardnessModal";

const plates = [
  // -------------
  // CHANGE PLATES
  // -------------
  {
    id: "changePlates",
    name: "Incremental Change Plates",
    categories: "plates",
    img: "changePlates2",
    price: " (Select Plate To See Price)",
    specs: {
      Hardness: hardnessModal("92 Shore A"),
      Diameter: "130-230mm",
      "Collar Opening": "50.4mm",
      "Weight Tolerance": "+/- 10g",
      Standard: "IWF Standard",
      Material: "Virgin rubber",
      "Sold In Pairs": '"Quantity: 1" = two plates',
    },
    data: [
      {
        outOfStock: true,
        id: "2.5lbChangePlate",
        name: "2.5lb Change Plate",
        price: "29.99",
        weight: "1134",
        url: "http://villainusa.com/products",
        categories: "plates",
        width: "18",
        length: "18",
        height: "2",
        quantity: "1",
        img: "changePlates9",
      },
      {
        outOfStock: true,
        id: "5lbChangePlate",
        name: "5lb Change Plate",
        price: "39.99",
        weight: "2268",
        url: "http://villainusa.com/products",
        categories: "plates",
        width: "21",
        length: "21",
        height: "2",
        quantity: "1",
        img: "changePlates10",
      },
      {
        outOfStock: false,
        id: "10lbChangePlate",
        name: "10lb Change Plate",
        price: "79.99",
        weight: "4536",
        url: "http://villainusa.com/products",
        categories: "plates",
        width: "23",
        length: "23",
        height: "3",
        quantity: "1",
        img: "changePlates8",
      },
      {
        id: "0.5kgChangePlate",
        name: "0.5kg Change Plate",
        price: "21.99",
        weight: "500",
        url: "http://villainusa.com/products",
        categories: "plates",
        width: "13",
        length: "13",
        height: "1",
        quantity: "1",
        img: "changePlates3",
      },
      {
        outOfStock: false,
        id: "1kgChangePlate",
        name: "1kg Change Plate",
        price: "29.99",
        weight: "1000",
        url: "http://villainusa.com/products",
        categories: "plates",
        width: "16",
        length: "16",
        height: "2",
        quantity: "1",
        img: "changePlates4",
      },
      {
        id: "1.5kgChangePlate",
        name: "1.5kg Change Plate",
        price: "31.99",
        weight: "2500",
        url: "http://villainusa.com/products",
        categories: "plates",
        width: "18",
        length: "18",
        height: "2",
        quantity: "1",
        img: "changePlates5",
      },
      {
        outOfStock: false,
        id: "2kgChangePlate",
        name: "2kg Change Plate",
        price: "39.99",
        weight: "2000",
        url: "http://villainusa.com/products",
        categories: "plates",
        width: "19",
        length: "19",
        height: "2",
        quantity: "1",
        img: "changePlates6",
      },
      {
        outOfStock: false,
        id: "2.5kgChangePlate",
        name: "2.5kg Change Plate",
        price: "43.99",
        weight: "2500",
        url: "http://villainusa.com/products",
        categories: "plates",
        width: "21",
        length: "21",
        height: "2",
        quantity: "1",
        img: "changePlates7",
      },
      {
        outOfStock: false,
        id: "5kgChangePlate",
        name: "5kg Change Plate",
        price: "79.99",
        weight: "5000",
        url: "http://villainusa.com/products",
        categories: "plates",
        width: "23",
        length: "23",
        height: "3",
        quantity: "1",
        img: "changePlates8",
      },
    ],
  },
  //-------------------
  // COMPETITION PLATES
  // ------------------
  {
    id: "competitionPlates",
    name: "Competition Bumper Plates",
    categories: "plates",
    img: "competitionPlates1",
    price: " (Select Plate To See Price)",
    specs: {
      Hardness: hardnessModal("92 Shore A"),
      Diameter: "450mm",
      "Collar Opening": "50.4mm",
      "Weight Tolerance": "+/- 10g",
      "Insert Type": "Steel disc, chrome plate",
      Material: "Virgin rubber",
      "Drop Test": "65,000 times",
      Thickness: "30-66mm",
      "Sold In Pairs": '"Quantity: 1" = two plates',
    },
    data: [
      {
        outOfStock: true,
        id: "25lbCompetitionPlate",
        name: "25lb Competition Plate",
        price: "187.99",
        weight: "11340",
        url: "http://villainusa.com/products",
        categories: "plates",
        width: "45",
        length: "45",
        height: "3",
        quantity: "1",
        img: "competitionPlates8",
      },
      {
        outOfStock: true,
        id: "35lbCompetitionPlate",
        name: "35lb Competition Plate",
        price: "237.99",
        weight: "15876",
        url: "http://villainusa.com/products",
        categories: "plates",
        width: "45",
        length: "45",
        height: "4",
        quantity: "1",
        img: "competitionPlates7",
      },
      {
        outOfStock: true,
        id: "45lbCompetitionPlate",
        name: "45lb Competition Plate",
        price: "279.99",
        weight: "20412",
        url: "http://villainusa.com/products",
        categories: "plates",
        width: "45",
        length: "45",
        height: "5",
        quantity: "1",
        img: "competitionPlates6",
      },
      {
        outOfStock: true,
        id: "55lbCompetitionPlate",
        name: "55lb Competition Plate",
        price: "329.99",
        weight: "24948",
        url: "http://villainusa.com/products",
        categories: "plates",
        width: "45",
        length: "45",
        height: "7",
        quantity: "1",
        img: "competitionPlates5",
      },
      {
        outOfStock: true,
        id: "10kgCompetitionPlate",
        name: "10kg Competition Plate",
        price: "183.99",
        weight: "10000",
        url: "http://villainusa.com/products",
        categories: "plates",
        width: "45",
        length: "45",
        height: "3",
        quantity: "1",
        img: "competitionPlates4",
      },
      {
        outOfStock: true,
        id: "15kgCompetitionPlate",
        name: "15kg Competition Plate",
        price: "223.99",
        weight: "15000",
        url: "http://villainusa.com/products",
        categories: "plates",
        width: "45",
        length: "45",
        height: "4",
        quantity: "1",
        img: "competitionPlates3",
      },
      {
        outOfStock: true,
        id: "20kgCompetitionPlate",
        name: "20kg Competition Plate",
        price: "279.99",
        weight: "20000",
        url: "http://villainusa.com/products",
        categories: "plates",
        width: "45",
        length: "45",
        height: "5",
        quantity: "1",
        img: "competitionPlates2",
      },
      {
        outOfStock: true,
        id: "25kgCompetitionPlate",
        name: "25kg Competition Plate",
        price: "327.99",
        weight: "25000",
        url: "http://villainusa.com/products",
        categories: "plates",
        width: "45",
        length: "45",
        height: "7",
        quantity: "1",
        img: "competitionPlates1",
      },
    ],
  },
  // --------------
  // ECONOMY PLATES
  // --------------
  {
    id: "economyPlates",
    name: "Economy Bumper Plates",
    categories: "plates",
    img: "economyPlates1",
    price: " (Select Plate To See Price)",
    specs: {
      Hardness: hardnessModal("85 Shore A"),
      Diameter: "450mm",
      "Collar Opening": "50.4mm",
      "Weight Tolerance": "+/- 1%",
      "Insert Type": "Stainless steel insert",
      Material: "Recycled rubber",
      "Drop Test": "45,000 times",
      Thickness: "26-91mm",
      "Sold In Pairs": '"Quantity: 1" = two plates',
    },
    data: [
      {
        outOfStock: false,
        id: "10lbEconomyPlate",
        name: "10lb Economy Plate",
        price: "65.99",
        weight: "4536",
        url: "http://villainusa.com/products",
        categories: "plates",
        width: "45",
        length: "45",
        height: "3",
        quantity: "1",
        img: "economyPlates5",
      },
      {
        outOfStock: false,
        id: "15lbEconomyPlate",
        name: "15lb Economy Plate",
        price: "81.99",
        weight: "6804",
        url: "http://villainusa.com/products",
        categories: "plates",
        width: "45",
        length: "45",
        height: "4",
        quantity: "1",
        img: "economyPlates5",
      },
      {
        outOfStock: false,
        id: "25lbEconomyPlate",
        name: "25lb Economy Plate",
        price: "103.99",
        weight: "11340",
        url: "http://villainusa.com/products",
        categories: "plates",
        width: "45",
        length: "45",
        height: "5",
        quantity: "1",
        img: "economyPlates9",
      },
      {
        outOfStock: false,
        id: "35lbEconomyPlate",
        name: "35lb Economy Plate",
        price: "147.99",
        weight: "15876",
        url: "http://villainusa.com/products",
        categories: "plates",
        width: "45",
        length: "45",
        height: "7",
        quantity: "1",
        img: "economyPlates8",
      },
      {
        outOfStock: false,
        id: "45lbEconomyPlate",
        name: "45lb Economy Plate",
        price: "195.99",
        weight: "20412",
        url: "http://villainusa.com/products",
        categories: "plates",
        width: "45",
        length: "45",
        height: "9",
        quantity: "1",
        img: "economyPlates7",
      },
      {
        outOfStock: false,
        id: "55lbEconomyPlate",
        name: "55lb Economy Plate",
        price: "223.99",
        weight: "24948",
        url: "http://villainusa.com/products",
        categories: "plates",
        width: "45",
        length: "45",
        height: "9",
        quantity: "1",
        img: "economyPlates6",
      },
      {
        outOfStock: false,
        id: "5kgEconomyPlate",
        name: "5kg Economy Plate",
        price: "71.99",
        weight: "5000",
        url: "http://villainusa.com/products",
        categories: "plates",
        width: "45",
        length: "45",
        height: "3",
        quantity: "1",
        img: "economyPlates5",
      },
      {
        outOfStock: false,
        id: "10kgEconomyPlate",
        name: "10kg Economy Plate",
        price: "99.99",
        weight: "10000",
        url: "http://villainusa.com/products",
        categories: "plates",
        width: "45",
        length: "45",
        height: "5",
        quantity: "1",
        img: "economyPlates4",
      },
      {
        outOfStock: false,
        id: "15kgEconomyPlate",
        name: "15kg Economy Plate",
        price: "139.99",
        weight: "15000",
        url: "http://villainusa.com/products",
        categories: "plates",
        width: "45",
        length: "45",
        height: "7",
        quantity: "1",
        img: "economyPlates3",
      },
      {
        outOfStock: false,
        id: "20kgEconomyPlate",
        name: "20kg Economy Plate",
        price: "195.99",
        weight: "20000",
        url: "http://villainusa.com/products",
        categories: "plates",
        width: "45",
        length: "45",
        height: "9",
        quantity: "1",
        img: "economyPlates2",
      },
      {
        id: "25kgEconomyPlate",
        name: "25kg Economy Plate",
        price: "235.99",
        weight: "25000",
        url: "http://villainusa.com/products",
        categories: "plates",
        width: "45",
        length: "45",
        height: "9",
        quantity: "1",
        img: "economyPlates1",
      },
    ],
  },
  // ---------------
  // TRAINING PLATES
  // ---------------
  {
    id: "trainingPlates",
    name: "Training Bumper Plates",
    categories: "plates",
    img: "trainingPlates1",
    price: " (Select Plate To See Price)",
    specs: {
      Hardness: hardnessModal("92 Shore A"),
      Diameter: "450mm",
      "Collar Opening": "50.4mm",
      "Weight Tolerance": "+/- 10g",
      "Insert Type": "Steel disc, chrome plate",
      Material: "Virgin rubber",
      "Drop Test": "65,000 times",
      Thickness: "30-66mm",
      "Sold In Pairs": '"Quantity: 1" = two plates',
    },
    data: [
      {
        outOfStock: true,
        id: "25lbTrainingPlate",
        name: "25lb Training Plate",
        price: "165.99",
        weight: "11340",
        url: "http://villainusa.com/products",
        categories: "plates",
        width: "45",
        length: "45",
        height: "3",
        quantity: "1",
        img: "trainingPlates4",
      },
      {
        outOfStock: true,
        id: "35lbTrainingPlate",
        name: "35lb Training Plate",
        price: "201.99",
        weight: "15876",
        url: "http://villainusa.com/products",
        categories: "plates",
        width: "45",
        length: "45",
        height: "4",
        quantity: "1",
        img: "trainingPlates3",
      },
      {
        outOfStock: true,
        id: "45lbTrainingPlate",
        name: "45lb Training Plate",
        price: "259.99",
        weight: "20412",
        url: "http://villainusa.com/products",
        categories: "plates",
        width: "45",
        length: "45",
        height: "5",
        quantity: "1",
        img: "trainingPlates2",
      },
      {
        outOfStock: true,
        id: "55lbTrainingPlate",
        name: "55lb Training Plate",
        price: "285.99",
        weight: "24948",
        url: "http://villainusa.com/products",
        categories: "plates",
        width: "45",
        length: "45",
        height: "7",
        quantity: "1",
        img: "trainingPlates1",
      },
      {
        outOfStock: true,
        id: "10kgTrainingPlate",
        name: "10kg Training Plate",
        price: "153.99",
        weight: "10000",
        url: "http://villainusa.com/products",
        categories: "plates",
        width: "45",
        length: "45",
        height: "3",
        quantity: "1",
        img: "trainingPlates4",
      },
      {
        outOfStock: true,
        id: "15kgTrainingPlate",
        name: "15kg Training Plate",
        price: "191.99",
        weight: "15000",
        url: "http://villainusa.com/products",
        categories: "plates",
        width: "45",
        length: "45",
        height: "4",
        quantity: "1",
        img: "trainingPlates3",
      },
      {
        outOfStock: true,
        id: "20kgTrainingPlate",
        name: "20kg Training Plate",
        price: "255.99",
        weight: "20000",
        url: "http://villainusa.com/products",
        categories: "plates",
        width: "45",
        length: "45",
        height: "5",
        quantity: "1",
        img: "trainingPlates2",
      },
      {
        outOfStock: true,
        id: "25kgTrainingPlate",
        name: "25kg Training Plate",
        price: "285.99",
        weight: "25000",
        url: "http://villainusa.com/products",
        categories: "plates",
        width: "45",
        length: "45",
        height: "7",
        quantity: "1",
        img: "trainingPlates1",
      },
    ],
  },
  // --------------
  // STRIPED PLATES
  // --------------
  {
    id: "stripedPlates",
    name: "Striped Bumper Plates",
    categories: "plates",
    img: "stripedPlates1",
    price: " (Select Plate To See Price)",
    specs: {
      Hardness: hardnessModal("92 Shore A"),
      Diameter: "450mm",
      "Collar Opening": "50.4mm",
      "Weight Tolerance": "+/- 10g",
      "Insert Type": "Steel disc, chrome plate",
      Material: "Virgin rubber",
      "Drop Test": "65,000 times",
      Thickness: "30-66mm",
      "Sold In Pairs": '"Quantity: 1" = two plates',
    },
    data: [
      {
        outOfStock: true,
        id: "25lbStripedPlate",
        name: "25lb Striped Plate",
        price: "175.99",
        weight: "11340",
        url: "http://villainusa.com/products",
        categories: "plates",
        width: "45",
        length: "45",
        height: "3",
        quantity: "1",
        img: "stripedPlates4",
      },
      {
        outOfStock: true,
        id: "35lbStripedPlate",
        name: "35lb Striped Plate",
        price: "219.99",
        weight: "15876",
        url: "http://villainusa.com/products",
        categories: "plates",
        width: "45",
        length: "45",
        height: "4",
        quantity: "1",
        img: "stripedPlates3",
      },
      {
        outOfStock: true,
        id: "45lbStripedPlate",
        name: "45lb Striped Plate",
        price: "263.99",
        weight: "20412",
        url: "http://villainusa.com/products",
        categories: "plates",
        width: "45",
        length: "45",
        height: "5",
        quantity: "1",
        img: "stripedPlates2",
      },
      {
        outOfStock: true,
        id: "55lbStripedPlate",
        name: "55lb Striped Plate",
        price: "307.99",
        weight: "24948",
        url: "http://villainusa.com/products",
        categories: "plates",
        width: "45",
        length: "45",
        height: "7",
        quantity: "1",
        img: "stripedPlates1",
      },
      {
        outOfStock: true,
        id: "10kgStripedPlate",
        name: "10kg Striped Plate",
        price: "165.99",
        weight: "10000",
        url: "http://villainusa.com/products",
        categories: "plates",
        width: "45",
        length: "45",
        height: "3",
        quantity: "1",
        img: "stripedPlates4",
      },
      {
        outOfStock: true,
        id: "15kgStripedPlate",
        name: "15kg Striped Plate",
        price: "203.99",
        weight: "15000",
        url: "http://villainusa.com/products",
        categories: "plates",
        width: "45",
        length: "45",
        height: "4",
        quantity: "1",
        img: "stripedPlates3",
      },
      {
        outOfStock: true,
        id: "20kgStripedPlate",
        name: "20kg Striped Plate",
        price: "253.99",
        weight: "20000",
        url: "http://villainusa.com/products",
        categories: "plates",
        width: "45",
        length: "45",
        height: "5",
        quantity: "1",
        img: "stripedPlates2",
      },
      {
        outOfStock: true,
        id: "25kgStripedPlate",
        name: "25kg Striped Plate",
        price: "297.99",
        weight: "25000",
        url: "http://villainusa.com/products",
        categories: "plates",
        width: "45",
        length: "45",
        height: "7",
        quantity: "1",
        img: "stripedPlates1",
      },
    ],
  },
  {
    id: "techniquePlates",
    name: "Technique Plates",
    categories: "plates",
    img: "techniquePlates1",
    price: " (Select Plate To See Price)",
    specs: {
      Diameter: "450mm",
      "Collar Opening": "50.6mm",
      Material: "Rigid plastic",
      Thickness: "80mm (2.5kg), 100mm (5kg)",
      "Sold In Pairs": '"Quantity: 1" = two plates',
    },
    data: [
      {
        id: "2.5kgTechniquePlate",
        name: "2.5kg Technique Plate",
        price: "133.99",
        weight: "2500",
        url: "http://villainusa.com/products",
        categories: "plates",
        width: "45",
        length: "45",
        height: "7",
        quantity: "1",
        img: "techniquePlates2",
      },
      {
        id: "5kgPlasticTechniquePlate",
        name: "5kg Technique Plate",
        price: "159.99",
        weight: "5000",
        url: "http://villainusa.com/products",
        categories: "plates",
        width: "45",
        length: "45",
        height: "9",
        quantity: "1",
        img: "techniquePlates3",
      },
    ],
  },
];

export default plates;
