const strengthEquipment = [
  {
    id: "vipr",
    name: "Functional Training Log",
    categories: "strengthEquipment",
    img: "vipr1",
    price: " (Select Item To See Price)",
    specs: {
      Material: "Thermoplastic Elastomer Rubber (TPR)",
      Diameter: "14cm",
      Length: "107cm",
    },
    data: [
      {
        id: "vipr6kg",
        name: "6kg Functional Training Log",
        price: "79.99",
        weight: "6000",
        url: "",
        categories: "strengthEquipment",
        width: "14",
        length: "107",
        height: "14",
        quantity: "1",
        img: "vipr1",
      },
      {
        id: "vipr8kg",
        name: "8kg Functional Training Log",
        price: "99.99",
        weight: "8000",
        url: "",
        categories: "strengthEquipment",
        width: "14",
        length: "107",
        height: "14",
        quantity: "1",
        img: "vipr1",
      },
    ],
  },
  {
    id: "fatGrips",
    name: "Thick Grip Trainer",
    categories: "strengthEquipment",
    img: "fatGrips1",
    price: " (Select Item To See Price)",
    specs: {
      Small: "Diameter: 50mm, Length: 100mm",
      Large: "Diameter: 57mm, Length: 125mm",
    },
    data: [
      {
        id: "fatGripsSmall",
        name: "Small Thick Grip Trainer",
        price: "24.99",
        weight: "300",
        url: "",
        categories: "strengthEquipment",
        width: "5",
        length: "12",
        height: "5",
        quantity: "1",
        img: "fatGrips1",
      },
      {
        id: "fatGripsLarge",
        name: "Large Thick Grip Trainer",
        price: "24.99",
        weight: "300",
        url: "",
        categories: "strengthEquipment",
        width: "5",
        length: "12",
        height: "5",
        quantity: "1",
        img: "fatGrips1",
      },
    ],
  },
  {
    id: "squatPad",
    name: "Squat Pad",
    price: "14.99",
    weight: "300",
    url: "",
    categories: "strengthEquipment",
    width: "10",
    length: "45",
    height: "10",
    quantity: "1",
    img: "squatPad1",
    specs: {
      Length: "45cm",
      Diameter: "10cm",
    },
  },
  {
    id: "powerSled",
    name: "Power Sled",
    price: "169.99",
    weight: "20000",
    url: "",
    categories: "strengthEquipment",
    width: "36",
    length: "56",
    height: "30",
    quantity: "1",
    img: "powerSled1",
    specs: {
      Height: "107cm",
      Length: "56cm",
      Width: "36cm",
    },
  },
  {
    id: "battleRope",
    name: "Battle Rope",
    categories: "strengthEquipment",
    img: "battleRope1",
    price: " (Select Item To See Price)",
    specs: {
      Length: "15m",
      Diameter: "38mm or 50mm",
    },
    data: [
      {
        id: "battleRope38mm",
        name: "38mm Battle Rope",
        price: "164.99",
        weight: "17500",
        url: "",
        categories: "strengthEquipment",
        width: "30",
        length: "30",
        height: "40",
        quantity: "1",
        img: "battleRope1",
      },
      {
        id: "battleRope50mm",
        name: "50mm Battle Rope",
        price: "199.99",
        weight: "17500",
        url: "",
        categories: "strengthEquipment",
        width: "30",
        length: "30",
        height: "40",
        quantity: "1",
        img: "battleRope1",
      },
    ],
  },
  {
    id: "medBall",
    name: "Medicine Balls",
    categories: "strengthEquipment",
    img: "medBall1",
    price: " (Select Ball To See Price)",
    specs: {
      Construction: "Rubber outer, hollow inner",
      Customization: "Available",
    },
    data: [
      {
        id: "medBall5lb",
        name: "5lb Medicine Ball",
        price: "14.99",
        weight: "2500",
        url: "",
        categories: "strengthEquipment",
        width: "28",
        length: "28",
        height: "28",
        quantity: "1",
        img: "medBall1",
      },
      {
        id: "medBall10lb",
        name: "10lb Medicine Ball",
        price: "16.99",
        weight: "4500",
        url: "",
        categories: "strengthEquipment",
        width: "28",
        length: "28",
        height: "28",
        quantity: "1",
        img: "medBall1",
      },
      {
        id: "medBall15lb",
        name: "15lb Medicine Ball",
        price: "19.99",
        weight: "6300",
        url: "",
        categories: "strengthEquipment",
        width: "28",
        length: "28",
        height: "28",
        quantity: "1",
        img: "medBall1",
      },
      {
        id: "medBall20lb",
        name: "20lb Medicine Ball",
        price: "24.99",
        weight: "9000",
        url: "",
        categories: "strengthEquipment",
        width: "28",
        length: "28",
        height: "28",
        quantity: "1",
        img: "medBall1",
      },
      {
        id: "medBall25lb",
        name: "25lb Medicine Ball",
        price: "29.99",
        weight: "11000",
        url: "",
        categories: "strengthEquipment",
        width: "28",
        length: "28",
        height: "28",
        quantity: "1",
        img: "medBall1",
      },
      {
        id: "medBall30lb",
        name: "30lb Medicine Ball",
        price: "33.99",
        weight: "14000",
        url: "",
        categories: "strengthEquipment",
        width: "28",
        length: "28",
        height: "28",
        quantity: "1",
        img: "medBall1",
      },
      {
        id: "medBall35lb",
        name: "35lb Medicine Ball",
        price: "37.99",
        weight: "1600",
        url: "",
        categories: "strengthEquipment",
        width: "28",
        length: "28",
        height: "28",
        quantity: "1",
        img: "medBall1",
      },
      {
        id: "medBall40lb",
        name: "40lb Medicine Ball",
        price: "49.99",
        weight: "18000",
        url: "",
        categories: "strengthEquipment",
        width: "28",
        length: "28",
        height: "28",
        quantity: "1",
        img: "medBall1",
      },
      {
        id: "medBall50lb",
        name: "50lb Medicine Ball",
        price: "64.99",
        weight: "22600",
        url: "",
        categories: "strengthEquipment",
        width: "28",
        length: "28",
        height: "28",
        quantity: "1",
        img: "medBall1",
      },
    ],
  },
  {
    id: "wallBall",
    name: "Wall Balls",
    categories: "strengthEquipment",
    img: "wallBall7",
    price: " (Select Ball To See Price)",
    specs: {
      Construction: "Faux leather outer, rubber liner, pellet filling",
      Customization: "Available",
    },
    data: [
      {
        id: "wallBall3kg",
        name: "3kg Wall Ball",
        price: "59.99",
        weight: "3000",
        url: "",
        categories: "strengthEquipment",
        width: "30",
        length: "30",
        height: "30",
        quantity: "1",
        img: "wallBall10",
      },
      {
        id: "wallBall4kg",
        name: "4kg Wall Ball",
        price: "64.99",
        weight: "4000",
        url: "",
        categories: "strengthEquipment",
        width: "30",
        length: "30",
        height: "30",
        quantity: "1",
        img: "wallBall9",
      },
      {
        id: "wallBall5kg",
        name: "5kg Wall Ball",
        price: "69.99",
        weight: "5000",
        url: "",
        categories: "strengthEquipment",
        width: "30",
        length: "30",
        height: "30",
        quantity: "1",
        img: "wallBall8",
      },
      {
        id: "wallBall6kg",
        name: "6kg Wall Ball",
        price: "74.99",
        weight: "6000",
        url: "",
        categories: "strengthEquipment",
        width: "30",
        length: "30",
        height: "30",
        quantity: "1",
        img: "wallBall7",
      },
      {
        id: "wallBall7kg",
        name: "7kg Wall Ball",
        price: "79.99",
        weight: "7000",
        url: "",
        categories: "strengthEquipment",
        width: "30",
        length: "30",
        height: "30",
        quantity: "1",
        img: "wallBall6",
      },
      {
        id: "wallBall8kg",
        name: "8kg Wall Ball",
        price: "84.99",
        weight: "8000",
        url: "",
        categories: "strengthEquipment",
        width: "30",
        length: "30",
        height: "30",
        quantity: "1",
        img: "wallBall5",
      },
      {
        id: "wallBall9kg",
        name: "9kg Wall Ball",
        price: "89.99",
        weight: "9000",
        url: "",
        categories: "strengthEquipment",
        width: "30",
        length: "30",
        height: "30",
        quantity: "1",
        img: "wallBall4",
      },
      {
        id: "wallBall10kg",
        name: "10kg Wall Ball",
        price: "94.99",
        weight: "10000",
        url: "",
        categories: "strengthEquipment",
        width: "30",
        length: "30",
        height: "30",
        quantity: "1",
        img: "wallBall3",
      },
      {
        id: "wallBall11kg",
        name: "11kg Wall Ball",
        price: "99.99",
        weight: "11000",
        url: "",
        categories: "strengthEquipment",
        width: "30",
        length: "30",
        height: "30",
        quantity: "1",
        img: "wallBall2",
      },
      {
        id: "wallBall12kg",
        name: "12kg Wall Ball",
        price: "104.99",
        weight: "12000",
        url: "",
        categories: "strengthEquipment",
        width: "30",
        length: "30",
        height: "30",
        quantity: "1",
        img: "wallBall1",
      },
    ],
  },
];

export default strengthEquipment;
