const weightliftingGear = [
  {
    id: "doWinShoe",
    name: "Do-Win Weightlifting Shoes",
    categories: "weightliftingGear",
    img: "doWinShoe1",
    price: " (Select Color To See Price)",
    specs: {
      Heel: "0.75in. plastic heel",
      Material: "Synthetic leather and nylon mesh upper",
      Features: "Flexible forefoot for full mobility",
      Sole: "Do-Win single sole design",
      Fastening: "Laces, mid-foot strap for secure fit",
    },
    data: [
      {
        id: "redShoe",
        name: "Red Do-Win Weightlifting Shoe",
        price: "174.99",
        weight: "1000",
        url: "",
        categories: "weightliftingGear",
        width: "23",
        length: "30",
        height: "15",
        custom2Name: "Size",
        custom2Options: "US Men's Size 6|US Men's Size 9|US Men's size 10",
        custom2Value: "US Men's Size 6",
        quantity: "1",
        img: "doWinShoe1",
      },
      {
        id: "yellowShoe",
        name: "Yellow Do-Win Weightlifting Shoe",
        price: "174.99",
        weight: "1000",
        url: "",
        categories: "weightliftingGear",
        width: "23",
        length: "30",
        height: "15",
        custom2Name: "Size",
        custom2Options: "US Men's Size 6|US Men's Size 9|US Men's size 10",
        custom2Value: "US Men's Size 6",
        quantity: "1",
        img: "doWinShoe2",
      },
    ],
  },
  {
    id: "pinkShoe",
    name: "Pink Wei-Rui Weightlifting Shoe",
    price: "49.99",
    weight: "1000",
    url: "",
    categories: "weightliftingGear",
    width: "23",
    length: "30",
    height: "15",
    custom2Name: "Size",
    custom2Options:
      "US Women's Size 4.5|US Women's Size 5.5|US Women's size 6.5|US Women's size 7.5",
    custom2Value: "US Women's Size 4.5",
    quantity: "1",
    img: "pinkShoe1",
    specs: {
      Heel: "0.75in. heel",
      Material: "Synthetic leather and nylon mesh upper",
      Features: "Flexible forefoot for full mobility",
      Sole: "Wei-Rui single sole design",
      Fastening: "Laces, mid-foot strap for secure fit",
    },
  },
  {
    id: "purpleShoe",
    name: "Purple Wei-Rui Weightlifting Shoe",
    price: "54.99",
    weight: "1000",
    url: "",
    categories: "weightliftingGear",
    width: "23",
    length: "30",
    height: "15",
    custom2Name: "Size",
    custom2Options:
      "US Men's Size 5|US Men's Size 6|US Men's size 9|US Men's size 9.5|US Men's size 10|US Men's size 11",
    custom2Value: "US Men's Size 5",
    quantity: "1",
    img: "purpleShoe1",
    specs: {
      Heel: "0.75in. heel",
      Material: "Synthetic leather and nylon mesh upper",
      Features: "Flexible forefoot for full mobility",
      Sole: "Wei-Rui single sole design",
      Fastening: "Laces, mid-foot strap for secure fit",
    },
  },
  {
    id: "weightliftingBelt",
    name: "Weightlifting Belt",
    price: "65.99",
    weight: "1000",
    url: "",
    categories: "weightliftingGear",
    width: "30",
    length: "30",
    height: "10",
    custom2Name: "Size",
    custom2Options: "Small|Medium|Large",
    custom2Value: "Small",
    quantity: "1",
    img: "weightliftingBelt1",
    specs: {
      Length: "Small: 105cm, Medium: 115cm, Large: 125cm",
      Material: "Cowhide",
    },
  },
  {
    id: "elasticWristWraps",
    name: "Elastic Wrist Wraps",
    price: "6.99",
    weight: "200",
    url: "",
    categories: "weightliftingGear",
    width: "7",
    length: "7",
    height: "7",
    custom2Name: "Size",
    custom2Options: "Small|Medium|Large",
    custom2Value: "Medium",
    quantity: "1",
    img: "elasticWristWraps1",
    specs: {
      Length: "Small: 30cm, Medium: 45cm, Large: 60cm",
    },
  },
  {
    id: "kneeSleeves",
    name: "Knee Sleeves",
    price: "16.99",
    weight: "400",
    url: "",
    categories: "weightliftingGear",
    width: "8",
    length: "8",
    height: "8",
    custom2Name: "Size",
    custom2Options: "X Small|Small|Medium|Large|X Large|XX Large",
    custom2Value: "Medium",
    quantity: "1",
    img: "kneeSleeves1",
    specs: {
      "X Small": "Circumference: 31cm",
      Small: "Circumference: 33cm",
      Medium: "Circumference: 35cm",
      Large: "Circumference: 37cm",
      "X Large": "Circumference: 40cm",
      "XX Large": "Circumference: 43cm",
    },
  },
  {
    id: "weightliftingStraps",
    name: "Weightlifting Straps",
    price: "11.99",
    weight: "50",
    url: "",
    categories: "weightliftingGear",
    width: "5",
    length: "8",
    height: "2",
    quantity: "1",
    img: "weightliftingStraps1",
    specs: {
      Material: "Cotton",
    },
  },
  {
    id: "cottonWristWraps",
    name: "Cotton Wrist Wraps",
    price: "11.99",
    weight: "50",
    url: "",
    categories: "weightliftingGear",
    width: "5",
    length: "5",
    height: "5",
    quantity: "1",
    img: "cottonWristWraps1",
    specs: {
      Material: "Cotton",
    },
  },
];

export default weightliftingGear;
